####################################################
#                                                  #
#   Author: Muszek                                 #
#   If you need help, join to discord              #
#   server: https://discord.com/invite/cT5MxqAYTd  #
#                                                  #
####################################################


Fire:
  Default_Duration: 3
Knockback:
  Item_Name: "&eKnockback Stick"
Freeze:
  Default_Duration: 5