name: EpicTroll
version: '1.1.9'
main: me.muszek_.troll.Troll
api-version: '1.20'
commands:
  troll:
    description: '&eMake a joke on players'
    aliases:
      - trolling
      - etroll
      - epictroll
    usage: |-
      /troll <arg>
